interval: 2
target: 192.168.1.1
logfile_name: "logfile.log"
pingwarning_threshold: 75
targets:
  - address: 192.168.1.1
    interval: 2
    pingwarning_threshold: 75
  - address: 192.168.1.2
    interval: 2
    pingwarning_threshold: 75