pinger:
  interval: 2
  target: 192.168.1.1
  pingwarning_threshold: 75
  verbosity: 1
logger:
  use_logger: true
  logfile_name: "logfile.log"
database:
  use_database: true
  host: localhost
  port: 5432
  dbname: cppinger
  user: cppinger
  password: example
